accounts/urls.py
#コード追加（5-6（P.200））
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignupView

app_name = 'accounts'

urlpatterns = [
  path('login/', LoginView.as_view(), name='login'),
  path('logout/', LogoutView.as_view(), name='logout'),
  path('signup/', SignupView.as_view(), name='signup'),
]

book/urls.py
from django.urls import path #コード追記（4-5）

from . import views #コード追記（4-5）

urlpatterns = [
  path('', views.index_view, name='index'),  #コード追記（5-2）（P.174）
  path('book/', views.LBView.as_view(), name='list-book'), #コード追記（4-5）
  path('book/<int:pk>/detail/', views.DBView.as_view(), name='detail-book'), #コード追記（4-6）
  path('book/create/', views.CBView.as_view(), name='create-book'), #コード追記（4-9）
  path('book/<int:pk>/delete/', views.DelBView.as_view(), name='delete-book'), #コード追記（4-10）（P.159）
  path('book/<int:pk>/update/', views.UBView.as_view(), name='update-book'), #コード追記（4-11）（P.161）
##  path('logout/', views.logout_view, name='logout'), #コード追記（5-5（P.192））
  path('book/<int:book_id>/review/', views.CRView.as_view(), name='review'), #コード追記（5-7（P.214））
]

bp/urls.py
from django.conf import settings #コード変更（5-8（P.239））
from django.conf.urls.static import static #コード変更（5-8（P.239））
from django.contrib import admin
from django.urls import path, include #コード追記

urlpatterns = [
    path('admin/', admin.site.urls),
##    path('accounts/', include('django.contrib.auth.urls')), #コード追記（5-4（P.185））
    path('accounts/', include('accounts.urls')), #コード変更（5-6（P.199））
    path('', include('book.urls')), #コード追記
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
##urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #コード変更（5-8（P.239））

accounts/models.py
from django.db import models

# Create your models here.

book/models.py
from django.db import models

# Create your models here.

# class SampleModel(models.Model): #コード追記
#     title = models.CharField(max_length = 100) #コード追記
#     number = models.IntegerField() #コード追記

CATEGORY = (('business', 'ビジネス'), ('life', '生活'), ('other', 'その他')) #コード追記

from .consts import MAX_RATE #コード追記（5-7（P.215））
RATE_CHOICES = [(x, str(x)) for x in range(0, MAX_RATE + 1)] #コード追記（5-7（P.215））


class Book(models.Model): #コード追記
  title = models.CharField(max_length = 100) #コード追記
  text = models.TextField() #コード追記
  thumbnail = models.ImageField(null=True, blank=True) #コード追記（5-8（P.232、P.234））
  category = models.CharField(
    max_length = 100,
    choices = CATEGORY
    ) #コード追記
  user = models.ForeignKey('auth.User', on_delete=models.CASCADE) #コード追記（5-11（P.251））

# ↓ 管理画面の「Book」にタイトルを表示させるために記述
  def __str__(self): #コード追記
    return self.title #コード追記


#コード追記（5-7（P.215））
class Review(models.Model):
  book = models.ForeignKey(Book, on_delete = models.CASCADE)
  title = models.CharField(max_length = 100)
  text = models.TextField()
  rate = models.IntegerField(choices = RATE_CHOICES)
  user = models.ForeignKey('auth.User', on_delete = models.CASCADE)

  def __str__(self):
    return self.title

accounts/forms.py
#コード追加（5-6（P.205））
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm) :
  class Meta :
    model = User
    fields = ('username',)

accounts/views.py
from django.shortcuts import render

# Create your views here.
#コード追加（5-6（P.204））
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import SignupForm

class SignupView(CreateView) :
  model = User
  form_class = SignupForm
  template_name = 'accounts/signup.html'
  success_url = reverse_lazy('index')

book/views.py
from django.contrib.auth.mixins import LoginRequiredMixin #コード追記（5-10（P.249））
from django.core.exceptions import PermissionDenied #コード追記（5-11（P.254））
from django.shortcuts import render, redirect #コード追記（5-5（P.193））

# Create your views here.
## from django.contrib.auth import logout #コード追記（5-5（P.193））
from django.urls import reverse, reverse_lazy #コード追記（4-9（P.157））（5-7（P.228））
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView #コード追記（4-5）（4-6）（4-9）（4-10（P.159））（4-11（P.159））
from .models import Book, Review #コード追記（4-5）（5-7（P.216））
from django.db.models import Avg #コード追記（5-12（P.260））

from django.core.paginator import Paginator #コード追記（5-14（P.270））
from .consts import ITEM_PER_PAGE #コード追記（5-14（P.270））

class LBView(LoginRequiredMixin, ListView): #コード追記（4-5）（5-10（P.249））
  template_name = 'book/book_list.html' #コード追記（4-5）
  model = Book #コード追記（4-5）
  paginate_by = ITEM_PER_PAGE #コード追記（5-14（P.277））

class DBView(LoginRequiredMixin, DetailView): #コード追記（4-6）（5-10（P.249））
  template_name = 'book/book_detail.html' #コード追記（4-6）
  model = Book #コード追記（4-6）

class CBView(LoginRequiredMixin, CreateView): #コード追記（4-9）（5-10（P.249））
  template_name = 'book/book_create.html' #コード追記（4-9）
  model = Book #コード追記（4-9）
  fields = ('title', 'text', 'category', 'thumbnail') #コード追記（4-9）コード修正（5-8）
  success_url = reverse_lazy('list-book') #コード追記（4-9（P.157））

  #コード修正（5-11（P.258））
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class DelBView(LoginRequiredMixin, DeleteView): #コード追記（4-10（P.159））（5-10（P.249））
  template_name = 'book/book_confirm_delete.html' #コード追記（4-10）
  model = Book #コード追記（4-10）
  success_url = reverse_lazy('list-book') #コード追記（4-10）

  #コード追記（5-11（P.258））
  def get_object(self, queryset=None):
    obj = super().get_object(queryset)

    if obj.user != self.request.user:
      raise PermissionDenied

    return obj

class UBView(LoginRequiredMixin, UpdateView): #コード追記（4-11（P.162））（5-10（P.249））
  template_name = 'book/book_update.html' #コード追記（4-11）
  model = Book #コード追記（4-11）
  fields = ('title', 'text', 'category', 'thumbnail') #コード追記（4-11）コード修正（5-8）
  # success_url = reverse_lazy('list-book') #コード追記（4-11）コード削除（5-11(p.256)）

  #コード追記（5-11（P.254））
  def get_object(self, queryset=None):
    obj = super().get_object(queryset)

    if obj.user != self.request.user:
      raise PermissionDenied

    return obj

  #コード追記（5-11（P.256））
  def get_success_url(self):
    return reverse('detail-book', kwargs={'pk':self.object.id})


from django.core.paginator import PageNotAnInteger, EmptyPage

#コード追記（5-2（P.175））
def index_view(request):
  # print('index_view is called')
  # return render(request, 'book/index.html', {'somedata': 100})
  # object_list = Book.objects.all() #コード追記（5-3（P.179））
  object_list = Book.objects.order_by('-id') #コード追記（5-3（P.182））コード修正（5-11（P.259））
  ranking_list = Book.objects.annotate(avg_rating = Avg('review__rate')).order_by('-avg_rating') #コード追記（5-12（P.260））  

  # コード追記（5-14（P.270））
  paginator = Paginator(ranking_list, ITEM_PER_PAGE)
  page_number = request.GET.get('page', 1)

  try:
    page_obj = paginator.page(page_number)
  except PageNotAnInteger:
    page_obj = paginator.page(1)
  except EmptyPage:
    page_obj = paginator.page(paginator.num_pages)

  # query = request.GET['number']
  # print(query)

  return render(
    request,
    'book/index.html',
    {
      'object_list': object_list,
      'ranking_list': ranking_list,
      'page_obj':page_obj,
      'item_per_page': ITEM_PER_PAGE, # オリジナルコード
    }
    ) #コード追記（5-3（P.179）） コード修正（5-12（P.260））コード修正（5-14（P.270））
  
#コード追記（5-5（P.193））
'''
def logout_view(request):
  logout(request)
  return redirect('index')
'''

#コード追記（5-7（P.216））
class CRView(CreateView):
  model = Review
  fields = ('book', 'title', 'text', 'rate')
  template_name = 'book/review_form.html'
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['book'] = Book.objects.get(pk=self.kwargs['book_id'])
    ## print(context)
    return context

#コード追記（5-7（P.227））
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

#コード追記（5-7（P.229））
  def get_success_url(self):
    return reverse('detail-book', kwargs={'pk': self.object.book.id})

accounts/templates/accounts/signup.html
<!-- #コード追記（5-6（P.211）） -->
{% extends 'base.html' %}

{% block title %}アカウント作成{% endblock %}
{% block h1 %}アカウント作成{% endblock %}

{% block content %}
  <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <input type="text" name="username" class="form-control my-4" placeholder="ユーザーID">
    <input type="password" name="password1" class="form-control mt-4" placeholder="パスワード">
    <input type="password" name="password2" class="form-control mt-4" placeholder="パスワード確認用">
    <small class="mb-2 d-block text-start">パスワードは8文字以上で設定してください。例：tanaka izWYFur3</small>

    {% if form.errors %}
      <span class="mb-2 small text-danger d-block text-start">利用できないユーザーIDやパスワードの可能性があります。入力内容を再度ご確認ください。</span>
    {% endif %}
    <button type="submit" class="btn btn-success m-2">アカウント作成</button>
  </form>
{% endblock %}

book/templates/book/book_confirm_delete.html
{% extends 'base.html' %} <!-- #コード追記（4-10）（p.160） -->

{% block title %}書籍削除{% endblock title %} <!-- #コード追記（4-10） -->

{% block content %} <!-- #コード追記（4-10） -->
<form method='POST'>{% csrf_token %}
  {{ form.as_p }}
  <button type='submit'>{{ object.title }}を削除する</button>
</form>
{% endblock content %}

book/templates/book/book_create.html
{% extends 'base.html' %} <!-- #コード追記（4-9） -->

{% block title %}書籍作成{% endblock title %} <!-- #コード追記（4-9） -->

{% block content %} <!-- #コード追記（4-9） -->
<form method='POST' enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">{% csrf_token %} <!-- #コード追記（4-9）（p.155） #コード修正（5-8）（p.244） -->
  {{ form.as_p }}
  <input type='submit' value='作成する' >
</form>
{% endblock content %} <!-- #コード追記（4-9） -->

book/templates/book/book_detail.html
{% extends 'base.html' %} <!-- #コード追記（4-8） -->

{% block title %}{{ object.title }}{% endblock %} <!-- #コード修正（4-13（P.170）） -->
{% block h1 %}書籍詳細{% endblock %} <!-- #コード修正（4-13（P.170）） -->

{% block content %} <!-- #コード追記（4-8） -->
<!-- #コード修正（4-13（P.170）） -->
<div class="p-4 m-4 bg-light border border-success rounded">
  <h2 class="text-success">{{ object.title }}</h2>
  <div class="card-body">
    <p>{{ object.text }}</p>

    <!-- #コード追記（5-13（P.268）） -->
    <div class="border p-4 mb-2">
      {% for review in object.review_set.all %}
      <div>
        <h3 class="h4">{{ review.title }}</h3>
        <div class="px-2">
          <span>（投稿ユーザー：{{ review.user.username }}）</span>
          <h6>評価：{{ review.rate }}点</h6>
          <p>{{ review.text }}</p>
        </div>
      </div>
      {% endfor %}
    </div>

    <a href="{% url 'list-book' %}" class="btn btn-primary">一覧へ</a> <!-- #コード修正（4-12(P.164)） -->
    <a href="{% url 'review' object.pk %}" class="btn btn-primary">レビューする</a> <!-- #コード修正（5-7 (P.230)） -->
    <a href="{% url 'update-book' object.pk %}" class="btn btn-primary">編集する</a> <!-- #コード追記（4-12(P.164)） -->
    <a href="{% url 'delete-book' object.pk %}" class="btn btn-primary">削除する</a> <!-- #コード追記（4-12(P.164)） -->
    <h6 class="card-title m-4">{{ object.category }}</h6>
  </div>
</div>
{% endblock content %} <!-- #コード追記（4-8） -->

book/templates/book/book_list.html
{% extends 'base.html' %} <!-- #コード追記（4-8） -->

{% block title %}書籍一覧{% endblock title %} <!-- #コード追記（4-8） -->
{% block h1 %}書籍一覧{% endblock h1 %} <!-- #コード追記（4-13） -->

{% block content %} <!-- #コード追記（4-8） -->
{% for item in object_list %}
<!-- #コード修正（4-13） -->
<div class="p-4 m-4 bg-lite border border-success rounded">
  <h2 class="text-success">{{ item.title }}</h2>
  <h6>カテゴリ：{{ item.category }}</h6>
  <div class="mt-3">
     <a href="{% url 'detail-book' item.pk %}">詳細へ</a> 
  </div>
</div>
<!-- #コード修正（4-13） -->
{% endfor %}
{% include 'book/components/pagination.html' %} <!-- コード追加（5-14（P.277）） -->
{% endblock content %} <!-- #コード追記（4-8） -->

book/templates/book/book_update.html
{% extends 'base.html' %} <!-- #コード追記（4-11（p.162）） -->

{% block title %}書籍修正{% endblock title %} <!-- #コード追記（4-11） -->

{% block content %} <!-- #コード追記（4-11） -->
<form method='POST' enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">{% csrf_token %}<!-- #コード修正（5-8）（p.244） -->
  {{ form.as_p }}
  <button type='submit'>{{ object.title }}を修正する</button>
</form>
{% endblock content %}

book/templates/book/components/pagination.html
<!-- コード追記（5-14（P.270）） -->
{% if page_obj.has_other_pages %}
<ul class="list-unstyled m-0 d-flex justify-content-between">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">&lt;&lt;前へ</a></li>
    {% else %}
    <li class="text-muted">&lt;&lt;前へ</li>
    {% endif %}

    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">次へ&gt;&gt;</a></li>
    {% else %}
    <li class="text-muted">次へ&gt;&gt;</li>
    {% endif %}
</ul>
{% endif %}

book/templates/book/index.html
<!-- コード追記（5-3（P.180）） -->
{% extends 'base.html' %}

{% block title %}本棚アプリ{% endblock %} <!-- コード修正（5-12（P.261）） -->
{% block h1 %}本棚アプリ{% endblock %} <!-- コード修正（5-12（P.261）） -->

{% block content %}
<!-- コード追記（5-12（P.261）） -->
<div class="row">
  <div class="col-9">
    {% for item in object_list %}
    <div class="p-4 m-4 bg-light border border-success rounded">
      <h2 class="text-success">{{ item.title }}</h2>
      {% if item.thumbnail %}<!-- このif文は管理画面の各アイテムの画像フィールドに登録が無い場合を考えてのこと、登録が一つでもないと「item.thumbnail.url」が使えず、エラーになる -->
        <img src="{{ item.thumbnail.url }}" class="img-thumbnail" /><!-- コード追記（5-8（P.242）） -->
      {% endif %}
      <h6>カテゴリ：{{ item.category }}</h6>
      <div class="mt-3">
        <a href="{% url 'detail-book' item.pk %}">詳細へ</a>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="col-3">
    <h2>評価順 TOP：{{ item_per_page }}</h2> <!-- コード修正（5-14（P.275）） -->
    {% for ranking_book in page_obj %} <!-- コード修正（5-14（P.275）） -->
    <div class="p-4 m-4 bg-light border border-success rounded">
      <h3 class="text-success h5">{{ ranking_book.title }}</h3>
      {% if ranking_book.thumbnail %} <!-- このif文は管理画面の各アイテムの画像フィールドに登録が無い場合を考えてのこと、登録が一つでもないと「ranking_book.thumbnail.url」が使えず、エラーになる -->
        <img src="{{ ranking_book.thumbnail.url }}" class="img-thumbnail">
      {% endif %}
      <h6>評価：{{ ranking_book.avg_rating | floatformat:2 }}点</h6> <!-- コード修正（5-12（P.265）） -->
      <a href="{% url 'detail-book' ranking_book.id %}">詳細を見る</a>
    </div>
    {% endfor %}
    {% include 'book/components/pagination.html' %} <!-- コード追加（5-14（P.275）） -->
  </div>
</div>
{% endblock content %}

book/templates/book/old/old_book_detail.html
{% extends 'base.html' %} <!-- #コード追記（4-8） -->

{% block title %}書籍詳細{% endblock title %} <!-- #コード追記（4-8） -->

{% block content %} <!-- #コード追記（4-8） -->
<div class="card">
  <h5 class="card-header">{{ object.title }}</h5>
  <div class="card-body">
    <p class="card-text">{{ object.text }}</p>
    <a href="{% url 'list-book' %}" class="btn btn-primary">一覧へ</a> <!-- #コード修正（4-12(P.164)） -->
    <a href="{% url 'update-book' object.pk %}" class="btn btn-primary">編集する</a> <!-- #コード追記（4-12(P.164)） -->
    <a href="{% url 'delete-book' object.pk %}" class="btn btn-primary">削除する</a> <!-- #コード追記（4-12(P.164)） -->
    <h6 class="card-title">{{ object.category }}</h6>
  </div>
</div>
{% endblock content %} <!-- #コード追記（4-8） -->

book/templates/book/old/old_book_list.html
{% extends 'base.html' %} <!-- #コード追記（4-8） -->

{% block title %}書籍一覧{% endblock title %} <!-- #コード追記（4-8） -->

{% block content %} <!-- #コード追記（4-8） -->
{% for item in object_list %}
<div class="card">
  <h5 class="card-header">{{ item.title }}</h5>
  <div class="card-body">
    <p class="card-text">{{ item.text }}</p>
    <a href="{% url 'detail-book' item.pk %}" class="btn btn-primary">Go Somewhere</a> <!-- #コード追記（4-12(P.163)） -->
    <h6 class="card-title">{{ item.category }}</h6>
  </div>
</div>
{% endfor %}
{% endblock content %} <!-- #コード追記（4-8） -->

book/templates/book/review_form.html
<!-- コード追記（5-7（P.217）） -->
{% extends 'base.html' %}

{% block title %}レビュー投稿{% endblock %}
{% block h1 %}レビュー投稿{% endblock %}

{% block content %}
  <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <label>対象書籍</label>
    <input class="form-control" value="{{ book.title }}" readonly>
    <label>タイトル</label>
    <input class="form-control" name="title">
    <label>本文</label>
    <textarea class="form-control" name="text" rows="3"></textarea>
    <label>星の数</label>
    <select class="form-control" name="rate">
      <option value="0">0（最低）</option>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3" selected>3（普通）</option>
      <option value="4">4</option>
      <option value="5">5（最高）</option>
    </select>
    <input type="hidden" name='book' value="{{ book.id }}">
    <button type="submit" class="btn btn-success mt-4">投稿する</button>
  </form>
{% endblock %}

templates/base.html
{% load static %} <!-- #コード追記（5-9）（P.246） -->
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title> <!-- #コード追記（4-8） -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'book/css/style.css' %}"> <!-- #コード追記（5-9） -->
  </head>
  <body>
    <nav class="navbar navbar-dark bg-success sticky-top"> <!-- #コード追記（4-13） -->
      <div class="navbar-nav d-flex flex-row">
        <a class="nav-link mx-3" href="{% url 'index' %}">TOP</a>
        <a class="nav-link mx-3" href="{% url 'list-book' %}">書籍一覧</a>
        <a class="nav-link mx-3"  href="{% url 'create-book' %}">書籍登録</a>
      </div>

      <!-- コード追記（5-5（P.194）） -->
      <div class="navbar-nav d-flex flex-row">
        {%if request.user.is_authenticated %}
          <!--<a class="nav-link mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>--><!-- コード修正（5-6（P.202）） -->

<!-- ★ LogoutViewのDjango5.0以降でのPOST対策 -->
<a href="#" onclick="logout(); return false;" class="nav-link mx-3">ログアウト</a>
<form id="LogoutForm" method="post" action="{% url 'accounts:logout' %}" style="display:none;">
  {% csrf_token %}
</form>
<script>
function logout() {
  document.getElementById("LogoutForm").submit();
}
</script>

        {% else %}
          <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a><!-- コード修正（5-6（P.202）） -->
          <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">会員登録</a><!-- コード修正（5-6（P.213）） -->
        {% endif %}
      </div>
    </nav>

    <div class="p-4">
      <h1>{% block h1 %}{% endblock %}</h1>
      {% block content %}{% endblock content %} <!-- #コード追記（4-8） -->
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>